plugins {
    id 'com.android.application'
}

android {
    namespace 'com.candlevision.expert'
    compileSdk 36

    defaultConfig {
        applicationId 'com.candlevision.expert'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '2.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.camera:camera-core:1.6.1'
    implementation 'androidx.camera:camera-camera2:1.6.1'
    implementation 'androidx.camera:camera-lifecycle:1.6.1'
    implementation 'androidx.camera:camera-view:1.6.1'
}
